"vim only
set viminfo+=n~/.config/vim/viminfo
set nocompatible

filetype off

filetype plugin indent on

"syntax highlighing
syntax on

"line numbers
set number

"fast scrollling
set ttyfast


" status bar
set laststatus=2

set showmode
set showcmd

" Set status line display
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ [BUFFER=%n]\ %{strftime('%c')}

 " Call the .vimrc.plug file
 if filereadable(expand("~/.vimrc.plug"))
     source ~/vimrc.plug
 endif

